use cutomer_behavior;
show databases;
use customer_behavior;
show tables;
select*from customer limit 10;
select*from customerss limit 10;


-- Q1. What is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue
from customerss
group by gender;

-- Q2. Which customer used discount but still spend more than the average purchase amount?
select customer_id, purchase_amount
from customerss
where discount_applied = "Yes" and purchase_amount >= (select avg(purchase_amount) from customerss);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,
       round(avg(review_rating),2) as avg_product_rating
from customerss
group by item_purchased
order by avg_product_rating desc
limit 5;

-- Q4. Compare the average purchase amounts between Standard and Express Shopping.alter
select shipping_type, round(avg(purchase_amount),2) as Avg_Purchase_Amount
from customerss
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers?
select subscription_status,
count(customer_id) as total_Customers,
round(avg(purchase_amount),2) as Avg_Spend,
round(sum(purchase_amount),2) as total_revenue
from customerss
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customerss
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment Customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment.alter
WITH customer_type AS (
  SELECT customer_id, previous_purchases,
         CASE
           WHEN previous_purchases = 1 THEN 'New'
           WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
           ELSE 'Loyal'
         END AS customer_segment
  FROM customerss
)
SELECT customer_segment, COUNT(*) AS `Number of Customers`
FROM customer_type
GROUP BY customer_segment;

-- Q8. Which are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customerss
    GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customerss
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customerss
group by age_group
order by total_revenue desc;